version: '3.8'

services:
  frontend:
    image: ahmedtrigui001/devops_project-2alinfo03-frontend
    ports:
      - "8085:4200"
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: root
  backend:
    image: ahmedtrigui001/devops_project-2alinfo03-backend
    command: sleep 3000
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops


