version: '3.8'

services:
  backend:
    image: ahmedtrigui001/devops_project-2alinfo03-backend
    ports:
      - "8083:8082"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops

  frontend:
    image: ahmedtrigui001/devops_project-2alinfo03-frontend
    ports:
      - "8085:80"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: root
