version: '3.8'

services:
  frontend:
    image: elyesjebali404/devops_project-2alinfo03-g2-frontend
    ports:
      - "8085:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: root
  backend:
    image: elyesjebali404/devops_project-2alinfo03-g2-backend
    ports:
      - "8083:8083"
    depends_on:
      - db
    restart: always
